version: '3.3'

services:
  app:
    build:
      context: ./serveur
      dockerfile: Dockerfile
      args:
        EMAIL: ${EMAIL}
        PASSWORD: ${PASSWORD}
        TRAINER_EMAIL: ${TRAINER_EMAIL}
        BASE_URL: ${BASE_URL}
    ports:
      - 8080:8080
    depends_on:
      - db
    env_file:
      - serveur/.env
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: wtc
    ports:
      - 5432:5432
  frontend:
    build:
      context: ./well_tennis_affichage_vu2
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - app