server:
    port: 8080
    error:
        include-stacktrace: "always"

spring:
    datasource:
        url: "jdbc:postgresql://db:5432/wtc"
        username: "postgres"
        password: "pwd"
        driver-class-name: "org.postgresql.Driver"
    jpa:
        properties: 
            hibernate:
                dialect: "org.hibernate.dialect.PostgreSQLDialect"
                format_sql: "true"
        show-sql: "false"
    mail:
        host: smtp.gmail.com
        port: 587
        username: ${EMAIL}
        password: ${PASSWORD}
        properties:
            mail:
                smtp:
                    ssl:
                        trust: smtp.gmail.com
                    auth: true
                    starttls:
                        enable: true
        protocol: smtp

management:
    endpoint:
        health:
            show-details: "always"

logging:
    level:
        well_tennis_club:
            projet: "DEBUG"

security:
    jwt:
        secret-key: cb5d4f92af1550dca925f3ec9e4622aa3dda7b6c3fe09e9c0c666fcebcebea9a
        expiration-time: 3600000

trainer_email: ${TRAINER_EMAIL}