spring:
  autoconfigure:
    exclude: "org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration,org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration"

springdoc:
  paths-to-exclude: "/error"
  default-produces-media-type: "application/json"
  swagger-ui:
    path: "/openapi/swagger-ui.html"
  api-docs:
    path: "/openapi/v3/api-docs"

security:
  jwt:
    secret-key: cb5d4f92af1550dca925f3ec9e4622aa3dda7b6c3fe09e9c0c666fcebcebea9a
    expiration-time: 3600000